### ISSUE TITLE
Future of this project with regards to VS 2017

### ISSUE THREAD

**Issue by stijnherreman** [editorconfig/editorconfig-visualstudio#49] opened 2016-11-18 15:04 UTC
I was just going over [the release notes of VS 2017](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes) and noticed this:

> New in RC Visual Studio editor now supports EditorConfig, which allows developers to define and maintain consistent coding style conventions between different editors and IDEs. See known issues for a list of known limitations in EditorConfig support in this RC release.

I suppose that this extension will be deprecated then in favour of the built-in support? Either way, thanks for all the work so far, since it probably encouraged Microsoft to add built-in support :)

**Comment by Mpdreamz** [comment] 2016-11-18 15:30
Unless someone wants to and sees a reason. I personally have no plans to bring this extension over to 2017.  
I do hope the limitations will be fixed soon (maybe first update). 

> EditorConfig is not supported in XML files
> Issue:
> Coding style conventions defined in .editorconfig are not applied when editing XML files.
> Workaround:
> There is no workaround at this time.

and

> EditorConfig insert_final_newline and trim_trailing_whitespace properties are not supported yet
> Issue:
> insert_final_newline and trim_trailing_whitespace properties defined in .editorconfig file have no effect.
> Workaround:
>There is no workaround at this time.

From what i gathered many more source formatting options will be expressible as editor config extension properties so i'm super hopeful this will receive continued love from Microsoft! :heart:

If someone feels these are important enough limitations to warrant a release for 2017 please let me or other members of the organization know, we happily accept PR's and add to the contributor list for the repos if needed!

**Comment by ffes** [comment] 2016-11-18 16:00
I think it is great the VS2017 has builtin EditorConfig support.

The release notes are about the RC. Those limitations you mention **may** even be fixed in the RTM.

**Comment by Mpdreamz** [comment] 2016-11-18 16:06
Yup some of the editorconfig extension properties that are going into roslyn just got pulled in a vs2017-rc2 branch: https://github.com/dotnet/roslyn/pull/15029

Good times ahead!

**Comment by Mpdreamz** [comment] 2016-11-18 16:11
FWIW i added a note on VS2017 and Resharper to the readme https://github.com/editorconfig/editorconfig-visualstudio

**Comment by spades789** [comment] 2017-01-10 18:00
I'm not sure if I am correct, but isn't the support in VS2017RC only for C#?
I would like to use EditorConfig in C++.

**Comment by ffes** [comment] 2017-01-10 20:05
Although I haven't tested the RC, I assume it is a Visual Studio feature, not a language specific one. So it should work for all languages that VS supports.

**Comment by spades789** [comment] 2017-01-10 20:35
Ah sorry. It works with C++, the problem was, that it doesn't support solution wide .editorconfig. I have to put it inside of every project.

**Comment by ffes** [comment] 2017-01-10 20:45
As said, haven't seen it in action yet but I assume when you put the .editorconfig file in the right place (the root directory of your solution) it will work as expected. Don't see why they would implement it differently.

Do you have any reference that a solution wide .editorconfig file doesn't work? Did you see this behavior yourself? Is the "root = true" set in the right place?

**Comment by spades789** [comment] 2017-01-10 21:22
So I tried it myself firt. Putting .editorconfig file into the solution folder does nothing, while putting it into the project folder results in correct indentation setting. The file is just simple:
```
root = true
[*]
end_of_line = lf
insert_final_newline = true
[*.{cpp,hpp}]
indent_style = space
indent_size = 4
```
There's also [this topic in the support page](https://developercommunity.visualstudio.com/content/problem/3575/only-limited-support-for-editorconfig-not-for-solu.html), but it's closed as not a bug.

**Comment by Mpdreamz** [comment] 2017-01-10 23:19
thanks for reporting @spades789 👍 

 I've pinged the folks over at MS (over email) that I know worked on the EditorConfig integration to continue the conversation.

It would be a real shame if the native editorconfig does not resolve files according to the spec.

**Comment by Mpdreamz** [comment] 2017-01-13 12:12
@spades789 MS let me know that it should work and now that I have VS2017 installed myself I can confirm it works as expected on my end. 

Also checkout: https://github.com/madskristensen/EditorConfigLanguage for additional editorconfig integrations (the inheritance visualizer could maybe help debug your problem).

**Closed** 2024-06-30 14:28 UTC
