### ISSUE TITLE
Visual studio crash with 'zombie' file

### ISSUE THREAD

**Issue by SteveALee** [editorconfig/editorconfig-visualstudio#32] opened 2015-12-02 13:33 UTC
I cannot reproduce this now but I had a `package.json` that was somehow listed in solution explorer but not part of the project. I can't figure how to get a file into that state again

When I saved the file I got a VS crash everytime. EditorConfig was the only extension I had added that was enabled.

See Microsoft/nodejstools#621

Feel free to close thais a not reproducible. I wanted to log it.

**Comment by Mpdreamz** [comment] 2016-06-17 15:07
closing this because I can not reproduce this on files not included in the project in `master`

Thanks for logging it though @SteveALee :+1:

**Closed by Mpdreamz** 2016-06-17 15:07 UTC

**Comment by SteveALee** [comment] 2016-06-17 15:10
Thanks anyway!
